### ISSUE TITLE
Request for my personal emby server WIN 10

### ISSUE THREAD

**Issue by parkercz** [XBigTK13X/snowby#25]
Hello , i wanna ask if you are willing to make adjustments to fit my Emby server. I watch mostly anime and 4k movies. (HDR) In 90% of cases i watch it locally on pc where is server. Other on Sony android TV. Using internal and external subtitles. I watch it over web app because of huge paywall in WIN 10 app. Screenshots how app looks like , so i can make decision if its for me.

Thank you in advance.

**Comment by XBigTK13X** [comment]
Thanks for reaching out. Let's use this issue to start gathering all the different tasks it would take to get Snowby running outside of my network.

[Here is a link to some screenshots](https://github.com/XBigTK13X/snowby/wiki/Screenshots). If after looking at those you want to continue down this road, please let me know here.

**Comment by parkercz** [comment]
Thank you for screenshots. Looking nice but ni think i will not be personally really satisfied with that look. 
Thank you for your effort and have a nice day.
